### ISSUE TITLE
Install/Remove assets and Update README

### ISSUE THREAD

**Issue by natsn** [htrg/wibi#6]
You asked for super clear instructions so here we go...

- Delete Ember, clear house.
- Install Angular, Bootstrap and FontAwesome.
- Edit README to reflect all changes, link to [Angular Docs](https://docs.angularjs.org/api)

**Comment by natsn** [comment]
Want to use Angular 2? https://www.youtube.com/watch?v=HmWm21cCAXM

I've heard it's pretty different.

**Comment by Borgaard** [comment]
* Scrubbed Ember from bower components and dependencies.
* Added Angular, Angular-ui, Angular-ui-Boostrap, Angular-resource for basic plugins and 3rd party modules, Angular-cookies because I got hungry, Angular-localStorage for saving data locally in a key/value store, protractor for Angular TDD, and also FontAwesome.
* Edited README to reflect changes to baseline Angular app, and will edit further as more information becomes available

###TODO
* Need to make module for ng-app tag
* Need to make a router and controller and make sure those js be loadin'z

**Comment by Borgaard** [comment]
The explicit instructions were much appreciated, thank you! :+1: Eventually I'm sure I'll get really comfortable with this codebase, but explicit instructions really do make a difference until I'm more familiar.

Angular 2 is very different from what I heard at the Fluent O'Reilly conference and through Angular developer mentors. It seems Angular 1 still has a large population with a lot of support and I'm most familiar with it, so that's what I used for this app.

**Comment by natsn** [comment]
:+1:
